apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: simple-app-prod
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: oci-devops
  source:
    repoURL: https://gitlab.com/<group>/oci-ai-devops-platform.git
    targetRevision: main
    path: kubernetes/overlays/prod
  destination:
    server: https://kubernetes.default.svc
    namespace: simple-app-prod
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - RespectIgnoreDifferences=true
    # Sync manual em prod — requer aprovação explícita
