apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: simple-app-hml

resources:
  - namespace.yaml
  - ../../base

labels:
  - pairs:
      env: hml
    includeSelectors: true

patches:
  - patch: |-
      - op: replace
        path: /spec/replicas
        value: 2
      - op: replace
        path: /spec/template/spec/containers/0/resources/requests/memory
        value: "128Mi"
      - op: replace
        path: /spec/template/spec/containers/0/resources/limits/memory
        value: "256Mi"
      - op: replace
        path: /spec/template/spec/containers/0/resources/requests/cpu
        value: "100m"
      - op: replace
        path: /spec/template/spec/containers/0/resources/limits/cpu
        value: "200m"
    target:
      kind: Deployment
      name: simple-app

  - patch: |-
      - op: replace
        path: /spec/rules/0/host
        value: app.hml.example.com
      - op: replace
        path: /spec/tls/0/hosts/0
        value: app.hml.example.com
    target:
      kind: Ingress
      name: simple-app

images:
  - name: simple-app
    newName: sa-saopaulo-1.ocir.io/<namespace>/oci-devops-hml/simple-app
    newTag: hml-latest
