apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: oci-vault
spec:
  provider:
    oracle:
      vault: ocid1.vault.oc1..replace-me
      region: sa-saopaulo-1
      auth:
        principalType: InstancePrincipal
