apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: simple-app-secrets
  namespace: simple-app-prod
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: oci-vault
    kind: ClusterSecretStore
  target:
    name: simple-app-secrets
    creationPolicy: Owner
  data:
    - secretKey: api-key
      remoteRef:
        key: simple-app-api-key
