apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - rbac/simple-app-role.yaml
  - network-policies/default-deny.yaml
  - network-policies/allow-ingress-to-app.yaml
  - external-secrets/cluster-secret-store.yaml
  - external-secrets/simple-app-secret.yaml
  - policies/require-security-context.yaml
