apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: simple-app-local

resources:
  - namespace.yaml
  - ../../base

labels:
  - pairs:
      env: local
    includeSelectors: true

patches:
  - patch: |-
      - op: replace
        path: /spec/replicas
        value: 2
      - op: add
        path: /spec/strategy
        value:
          type: RollingUpdate
          rollingUpdate:
            maxSurge: 0
            maxUnavailable: 1
      - op: replace
        path: /spec/template/spec/containers/0/resources/requests/memory
        value: "64Mi"
      - op: replace
        path: /spec/template/spec/containers/0/resources/limits/memory
        value: "128Mi"
      - op: replace
        path: /spec/template/spec/containers/0/resources/requests/cpu
        value: "50m"
      - op: replace
        path: /spec/template/spec/containers/0/resources/limits/cpu
        value: "100m"
      - op: replace
        path: /spec/template/spec/containers/0/imagePullPolicy
        value: IfNotPresent
      - op: add
        path: /spec/template/spec/affinity
        value:
          nodeAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
              nodeSelectorTerms:
                - matchExpressions:
                    - key: node-role.kubernetes.io/control-plane
                      operator: DoesNotExist
          podAntiAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
              - labelSelector:
                  matchLabels:
                    app: simple-app
                    env: local
                topologyKey: kubernetes.io/hostname
      - op: add
        path: /spec/template/spec/topologySpreadConstraints
        value:
          - maxSkew: 1
            topologyKey: kubernetes.io/hostname
            whenUnsatisfiable: DoNotSchedule
            labelSelector:
              matchLabels:
                app: simple-app
                env: local
    target:
      kind: Deployment
      name: simple-app

  - patch: |-
      - op: replace
        path: /spec/rules/0/host
        value: localhost
      - op: replace
        path: /spec/tls/0/hosts/0
        value: localhost
    target:
      kind: Ingress
      name: simple-app

images:
  - name: simple-app
    newName: simple-app
    newTag: local
